version: '3.8'

services:
  # Conversation Analyzer Service
  conversation-analyzer:
    build: .
    container_name: conversation-analyzer
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 6000
      WS_PORT: 6001
      CASE_RECORD_API_URL: http://case-record-server:5000/api
      SENTIMENT_API_URL: http://sentiment-api:8000
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: info
      ANALYSIS_INTERVAL_MS: 5000
      AUTO_CASE_CREATION_ENABLED: true
    ports:
      - "6000:6000"
      - "6001:6001"
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - conversation-network

  # Redis for caching and queues
  redis:
    image: redis:7.2-alpine
    container_name: conversation-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - conversation-network

  # Optional: Case Record API (if running separately)
  # case-record-server:
  #   image: case-record-server:latest
  #   container_name: case-record-server
  #   environment:
  #     NODE_ENV: development
  #     PORT: 5000
  #     MONGODB_URI: mongodb://mongodb:27017/case-record-db
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - conversation-network

  # Optional: Sentiment Analysis API (mock service)
  sentiment-api:
    image: nginx:alpine
    container_name: sentiment-api-mock
    ports:
      - "8000:80"
    volumes:
      - ./mock-sentiment-api.conf:/etc/nginx/conf.d/default.conf
    networks:
      - conversation-network

volumes:
  redis_data:

networks:
  conversation-network:
    driver: bridge
